# Challenges for open source data and metadata standards, and some solutions

## Too much flexibility, or too little

It's a story as old as time (or at least as old as standards): users fail to
consider existing standards, or perceive an existing standard as not offering
enough flexibility to cover some use case, and they embark on the development
of a new standard [^1].

[^1]: So old in fact that an oft-cited [XKCD comic](https://xkcd.com/927/) has
been devoted to it.

<!--
Not sure if it warrants its own section, but in my opinion, a more common
reason for people not to adopt existing standards is the _perceived_ risk of
adopting
1. something you do not know (it may be difficult to figure out if a
standard definitely solves my problem, and it may be expensive to figure out.
Additionally, the persons having to make the decision may lack the skills to
make an informed judgement);
2. something you don't control (compromises made in the further development of
a standard may make them unusable for my purposes);
3. something whose development pace you don't control (open source can move
very slowly, there is no guarantee that PRs will be merged or even
appreciated, etc).

With all of these perceived downsides, making a new standard every time may be
the expected outcome.

If we do want a paragraph along the lines of the above, we should try to collect
ideas on what advise a standard of standards should give on promoting adoption
of existing standards.
-->

Another failure is the mismatch between developers of the standard and users.
There is an inherent gap in both interest and ability to engage with the
technical details undergirding standards and their development between the
developers of the standard and their users. In extreme cases, these interests
may be at odds, as developers implement sophisticated mechanisms to automate
the creation of the standard or advocate for more technically advanced
mechanisms for evolving the standard, leaving potential users sidelined in the
development of the standard, and limiting their ability to provide feedback
about the practical implications of changes to the standards.

## Unclear pathways for standards success

Standards typically develop organically through sustained and persistent efforts from dedicated
groups of data practitioners. These include scientists and the broader ecosystem of data curators and users. However there is no playbook on the structure and components of a data standard, or the pathway that moves a data implementation to a data standard.
As a result, data standardization lacks formal avenues for research grants.

## Cross domain funding gaps

Data standardization investment is justified if the standard is generalizable beyond any specific science domain. However while the use cases are domain sciences based, data standardization is seen as a data infrastructure and not a science investment. Moreover due to how science research funding works, scientists lack incentives to work across domains, or work on infrastructure problems.

## Data instrumentation issues

Data for scientific observations are often generated by proprietary instrumentation due to commercialization or other profit driven incentives. There is lack of regulatory oversight to adhere to available standards or evolve Significant data transformation is required to get data to a state that is amenable to standards, if available. If not available, there is lack of incentive to set aside investment or resources to invest in establishing data standards.

## Sustainability

## The importance of automated validation


