# Opportunities and risks for open-source standards {#sec-opportunities}

At the same time, these tools and practices are associated with risks that need
to be mitigated.

## Flexibility vs. stability

One of the defining characteristics of OSS is its dynamism and its rapid
evolution. Because OSS can be used by anyone and, in most cases, contributions
can be made by anyone, innovations flow into OSS in a bottom-up fashion from
user/developers. Pathways to contribution by members of the community are often
well-defined: both from the technical perspective (e.g., through a pull request
on GitHub, or other similar mechanisms), as well as from the social perspective
(e.g., whether contributors need to accept certain licensing conditions through
a contributor licensing agreement) and the socio-technical perspective (e.g.,
how many people need to review a contribution, what are the timelines for a
contribution to be reviewed and accepted, what are the release cycles of the
software that make the contribution available to a broader community of users,
etc.). Similarly, open-source standards may also find themselves addressing use
cases and solutions that were not originally envisioned through bottom-up
contributions of members of a research community to which the standard
pertains. However, while this dynamism provides an avenue for flexibility it
also presents a source of tension. This is because data and metadata standards
apply to already existing datasets, and changes may affect the compliance of
these existing datasets. Similarly, analysis technology stacks that are
developed based on an existing version of a standard have to adapt to the
introduction of new ideas and changes into a standard. Dynamic changes of this
sort therefore risk causing a loss of faith in the standard by a user
community, and migration away from the standard. Similarly, if a standard
evolves too rapidly, users may choose to stick to an outdated version of a
standard for a long time, creating strains on the community of developers and
maintainers of a standard who will need to accommodate long deprecation cycles.

## Mismatches between standards developers and user communities

There is an inherent gap in both interest and ability to engage with the
technical details undergirding standards and their development between the core
developers of the standard and their users. In extreme cases, these interests
may even be at odds, as developers implement sophisticated mechanisms to
automate the creation and validation of the standard or advocate for more
technically advanced mechanisms for evolving the standard. These advanced
capabilities offer more robust development practices and consistency in cases
where the standards are complex and elaborate. On the other hand, they may end
up leaving potential users sidelined in the development of the standard, and
limiting their ability to provide feedback about the practical implications of
changes to the standards.

## Unclear pathways for standards success

Standards typically develop organically through sustained and persistent
efforts from dedicated groups of data practitioners. These include scientists
and the broader ecosystem of data curators and users. However, there is no
playbook on the structure and components of a data standard, or the pathway
that moves a data implementation to a data standard. As a result, data
standardization lacks formal avenues for success and recognition, for example through dedicated research grants (and see @sec-cross-sector)

## Cross-domain funding gaps

Data standardization investment is justified if the standard is generalizable
beyond any specific science domain. However while the use cases are domain
sciences based, data standardization is seen as a data infrastructure and not a
science investment. Moreover due to how science research funding works,
scientists lack incentives to work across domains, or work on infrastructure
problems.

## Data instrumentation issues

Data for scientific observations are often generated by proprietary
instrumentation due to commercialization or other profit driven incentives.
There islack of regulatory oversight to adhere to available standards or evolve
Significant data transformation is required to get data to a state that is
amenable to standards, if available. If not available, there is lack of
incentive to set aside investment or resources to invest in establishing data
standards.

## Sustainability

## The importance of automated validation

## Harnessing new computing paradigms and technologies

Open-source standards development faces the challenges of adapting to new
technologies The development of standards that are well-Cloud computing
provides

